export const evaluationsData = [
  {
    id: "1",
    studentName: "Nguyễn Văn A",
    studentId: "SV001",
    subject: "Toán Học",
    class: "10A",
    teacher: "Thầy Trần Minh",
    submitted: true,
    submittedDate: "2025-10-15T10:30:00Z",
    completionPercentage: 100,
    criteria: [
      {
        name: "Kiến Thức Lý Thuyết",
        description: "Nắm vững các khái niệm và định lý cơ bản",
        score: 8,
      },
      {
        name: "Kỹ Năng Giải Bài Tập",
        description: "Khả năng áp dụng kiến thức vào bài tập",
        score: 7,
      },
      {
        name: "Tham Gia Lớp",
        description: "Sự tích cực trong các hoạt động lớp",
        score: 9,
      },
      {
        name: "Bài Tập Về Nhà",
        description: "Chất lượng và độ hoàn thành bài tập",
        score: 8,
      },
    ],
    notes: "Học sinh có tiến bộ tốt, cần tập trung hơn vào các bài toán khó.",
  },
  {
    id: "2",
    studentName: "Trần Thị B",
    studentId: "SV002",
    subject: "Toán Học",
    class: "10A",
    teacher: "Thầy Trần Minh",
    submitted: true,
    submittedDate: "2025-10-14T14:20:00Z",
    completionPercentage: 100,
    criteria: [
      {
        name: "Kiến Thức Lý Thuyết",
        description: "Nắm vững các khái niệm và định lý cơ bản",
        score: 9,
      },
      {
        name: "Kỹ Năng Giải Bài Tập",
        description: "Khả năng áp dụng kiến thức vào bài tập",
        score: 9,
      },
      {
        name: "Tham Gia Lớp",
        description: "Sự tích cực trong các hoạt động lớp",
        score: 8,
      },
      {
        name: "Bài Tập Về Nhà",
        description: "Chất lượng và độ hoàn thành bài tập",
        score: 9,
      },
    ],
    notes: "Học sinh xuất sắc, có thể tham gia các cuộc thi toán học.",
  },
  {
    id: "3",
    studentName: "Lê Văn C",
    studentId: "SV003",
    subject: "Toán Học",
    class: "10A",
    teacher: "Thầy Trần Minh",
    submitted: false,
    submittedDate: null,
    completionPercentage: 60,
    criteria: [
      {
        name: "Kiến Thức Lý Thuyết",
        description: "Nắm vững các khái niệm và định lý cơ bản",
        score: 0,
      },
      {
        name: "Kỹ Năng Giải Bài Tập",
        description: "Khả năng áp dụng kiến thức vào bài tập",
        score: 0,
      },
      {
        name: "Tham Gia Lớp",
        description: "Sự tích cực trong các hoạt động lớp",
        score: 6,
      },
      {
        name: "Bài Tập Về Nhà",
        description: "Chất lượng và độ hoàn thành bài tập",
        score: 6,
      },
    ],
    notes: "",
  },
  {
    id: "4",
    studentName: "Phạm Thị D",
    studentId: "SV004",
    subject: "Toán Học",
    class: "10A",
    teacher: "Thầy Trần Minh",
    submitted: true,
    submittedDate: "2025-10-13T09:15:00Z",
    completionPercentage: 100,
    criteria: [
      {
        name: "Kiến Thức Lý Thuyết",
        description: "Nắm vững các khái niệm và định lý cơ bản",
        score: 7,
      },
      {
        name: "Kỹ Năng Giải Bài Tập",
        description: "Khả năng áp dụng kiến thức vào bài tập",
        score: 8,
      },
      {
        name: "Tham Gia Lớp",
        description: "Sự tích cực trong các hoạt động lớp",
        score: 7,
      },
      {
        name: "Bài Tập Về Nhà",
        description: "Chất lượng và độ hoàn thành bài tập",
        score: 7,
      },
    ],
    notes: "Học sinh có khả năng tốt, cần phát triển thêm kỹ năng giải quyết vấn đề.",
  },
  {
    id: "5",
    studentName: "Hoàng Văn E",
    studentId: "SV005",
    subject: "Toán Học",
    class: "10A",
    teacher: "Thầy Trần Minh",
    submitted: false,
    submittedDate: null,
    completionPercentage: 40,
    criteria: [
      {
        name: "Kiến Thức Lý Thuyết",
        description: "Nắm vững các khái niệm và định lý cơ bản",
        score: 0,
      },
      {
        name: "Kỹ Năng Giải Bài Tập",
        description: "Khả năng áp dụng kiến thức vào bài tập",
        score: 0,
      },
      {
        name: "Tham Gia Lớp",
        description: "Sự tích cực trong các hoạt động lớp",
        score: 4,
      },
      {
        name: "Bài Tập Về Nhà",
        description: "Chất lượng và độ hoàn thành bài tập",
        score: 4,
      },
    ],
    notes: "",
  },
]
